name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print message
      run: echo "Hello, CI!"

    - name: Compile C++ file
      run: |
        g++ hello.cpp -o hello
      continue-on-error: false

    - name: Archive the executable
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: hello_executable
        path: ./hello
